// NOTE: NBA.com and ESPN's public data APIs both reject requests from this extension (403),
// the same way they reject requests from Vercel — this was confirmed by testing both from a
// real logged-in Chrome session. So this background script makes NO outbound network calls
// at all. Player stats come from Yahoo's own page (read by yahoo-content.js, which already
// includes each player's season-average per-game line). The only other input a projection
// needs — how many games a team has in the coming days — comes from a schedule bundled into
// the extension at build time (extension/data/schedule.json, generated by
// scripts/build-schedule.cjs) rather than fetched live.

const SCHEDULE_URL = chrome.runtime.getURL('data/schedule.json');
const MAX_TEAMS = 30;
const MAX_WINDOW_DAYS = 60;

chrome.runtime.onInstalled.addListener(() => {
  chrome.storage.local.set({ companionVersion: '0.3.0', readOnly: true });
});

let scheduleCache = null;

async function loadSchedule() {
  if (scheduleCache) return scheduleCache;
  const response = await fetch(SCHEDULE_URL);
  if (!response.ok) throw new Error(`schedule_load_failed_${response.status}`);
  scheduleCache = await response.json();
  return scheduleCache;
}

function isValidDate(value) {
  return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value);
}

function sanitizeTeams(rawTeams) {
  if (!Array.isArray(rawTeams)) return [];
  return [...new Set(
    rawTeams
      .filter((team) => typeof team === 'string')
      .map((team) => team.trim().toUpperCase())
      .filter((team) => /^[A-Z]{2,4}$/.test(team)),
  )].slice(0, MAX_TEAMS);
}

async function handleScheduleRequest(rawPayload) {
  const teams = sanitizeTeams(rawPayload && rawPayload.teams);
  const startDate = isValidDate(rawPayload && rawPayload.startDate) ? rawPayload.startDate : null;
  const endDate = isValidDate(rawPayload && rawPayload.endDate) ? rawPayload.endDate : null;

  if (teams.length === 0 || !startDate || !endDate || endDate < startDate) {
    return { gamesByTeam: {}, scheduleCoverage: null, errors: ['invalid_request'] };
  }
  const windowDays = (new Date(`${endDate}T00:00:00Z`) - new Date(`${startDate}T00:00:00Z`)) / 86400000;
  if (windowDays > MAX_WINDOW_DAYS) {
    return { gamesByTeam: {}, scheduleCoverage: null, errors: ['window_too_large'] };
  }

  let schedule;
  try {
    schedule = await loadSchedule();
  } catch {
    return { gamesByTeam: {}, scheduleCoverage: null, errors: ['schedule_unavailable'] };
  }

  const errors = [];
  const coverage = schedule.coverage || null;
  if (coverage && (endDate < coverage.start || startDate > coverage.end)) {
    errors.push('window_outside_bundled_schedule');
  }

  const gamesByTeam = {};
  teams.forEach((team) => {
    const teamGames = (schedule.teams && schedule.teams[team]) || [];
    gamesByTeam[team] = teamGames
      .filter((game) => game.date >= startDate && game.date <= endDate && game.status !== 'postponed' && game.status !== 'canceled')
      .map((game) => ({ date: game.date, opponent: game.opponent, home: game.home }));
    if (!schedule.teams || !schedule.teams[team]) errors.push(`unknown_team:${team}`);
  });

  return { gamesByTeam, scheduleCoverage: coverage, errors };
}

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (!message || message.type !== 'NBA_ASSISTANT_SCHEDULE_REQUEST') return false;
  handleScheduleRequest(message.payload)
    .then((result) => sendResponse({ type: 'NBA_ASSISTANT_SCHEDULE_RESPONSE', payload: result }))
    .catch((error) => sendResponse({
      type: 'NBA_ASSISTANT_SCHEDULE_RESPONSE',
      payload: { gamesByTeam: {}, scheduleCoverage: null, errors: [error instanceof Error ? error.message : 'unknown_error'] },
    }));
  return true;
});
